# Generated by Django 5.2.6 on 2025-10-09 16:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0002_alter_factura_options_alter_factura_estado_and_more"),
        ("pagos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pago",
            options={"ordering": ["-fecha_pago"]},
        ),
        migrations.AddField(
            model_name="pago",
            name="numero_comprobante",
            field=models.CharField(
                blank=True,
                help_text="Número de referencia del comprobante",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="comprobante",
            field=models.FileField(
                blank=True, null=True, upload_to="comprobantes/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="fecha_pago",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pago",
            name="tipo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("cheque", "Cheque"),
                    ("tarjeta_credito", "Tarjeta de Crédito"),
                    ("tarjeta_debito", "Tarjeta de Débito"),
                    ("consignacion", "Consignación"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["factura", "fecha_pago"], name="pagos_pago_factura_62f2f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["usuario_registro", "fecha_pago"],
                name="pagos_pago_usuario_ff6210_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["tipo_pago"], name="pagos_pago_tipo_pa_0a14ec_idx"
            ),
        ),
    ]
