# Generated by Django 5.2.6 on 2025-10-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0004_factura_tipo_factura_facturas_fa_tipo_53a908_idx"),
        ("pagos", "0002_alter_pago_options_pago_numero_comprobante_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="estado",
            field=models.CharField(
                choices=[
                    ("registrado", "Registrado"),
                    ("confirmado", "Confirmado"),
                    ("anulado", "Anulado"),
                ],
                default="registrado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="fecha_confirmacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="usuario_confirmacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_confirmados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["estado"], name="pagos_pago_estado_c1c831_idx"),
        ),
    ]
