# Generated by Django 5.2.6 on 2025-10-21 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0006_factura_cliente_sucursal_and_more"),
        ("pagos", "0004_pago_descuento_pago_ica_pago_nota_pago_retencion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("banco", models.CharField(blank=True, max_length=100, null=True)),
                ("numero", models.CharField(blank=True, max_length=50, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="pago",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="<numero_factura>-NNN generado automáticamente al crear",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pago",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Referencia de transferencia/cheque, etc.",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="cuenta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pagos.cuentapago",
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["codigo"], name="pagos_pago_codigo_de6c72_idx"),
        ),
    ]
