# Generated by Django 5.2 on 2025-10-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_cuentapago_pago_codigo_pago_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_b64',
            field=models.TextField(blank=True, null=True, help_text='Contenido base64 del comprobante (imagen/pdf) si no se adjunta archivo'),
        ),
    ]
