# Generated by Django 5.2 on 2025-10-22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_pago_comprobante_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobante',
        ),
    ]
