# Generated by Django 5.2.6 on 2025-10-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facturas", "0002_alter_factura_options_alter_factura_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vencimiento", "Vencimiento de Factura"),
                            ("pago_parcial", "Pago Parcial Recibido"),
                            ("sin_pagos", "Sin Pagos por Tiempo Prolongado"),
                            ("monto_alto", "Factura de Monto Alto"),
                            ("custom", "Personalizada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "dias_anticipacion",
                    models.IntegerField(
                        blank=True,
                        help_text="Días antes del vencimiento para alertar",
                        null=True,
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto mínimo para generar alerta",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "dias_sin_actividad",
                    models.IntegerField(
                        blank=True,
                        help_text="Días sin actividad para alertar",
                        null=True,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Alerta",
                "verbose_name_plural": "Tipos de Alertas",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recibir_email", models.BooleanField(default=False)),
                ("recibir_notificacion", models.BooleanField(default=True)),
                (
                    "dias_anticipacion_custom",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "monto_minimo_custom",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alertas.tipoalerta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Alerta",
                "verbose_name_plural": "Configuraciones de Alertas",
                "unique_together": {("usuario", "tipo_alerta")},
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nueva", "Nueva"),
                            ("leida", "Leída"),
                            ("procesada", "Procesada"),
                            ("descartada", "Descartada"),
                        ],
                        default="nueva",
                        max_length=15,
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_leida", models.DateTimeField(blank=True, null=True)),
                ("fecha_procesada", models.DateTimeField(blank=True, null=True)),
                (
                    "datos_contexto",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales sobre la alerta",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="facturas.factura",
                    ),
                ),
                (
                    "usuario_destinatario",
                    models.ForeignKey(
                        help_text="Usuario que debe ver esta alerta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_procesado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_procesadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="alertas.tipoalerta",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario_destinatario", "estado"],
                        name="alertas_ale_usuario_38dea6_idx",
                    ),
                    models.Index(
                        fields=["factura", "estado"],
                        name="alertas_ale_factura_2ea2cd_idx",
                    ),
                    models.Index(
                        fields=["prioridad", "fecha_generacion"],
                        name="alertas_ale_priorid_9e0980_idx",
                    ),
                ],
            },
        ),
    ]
