# Generated by Django 5.2.6 on 2025-10-21 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poblacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "distribuidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poblaciones_distribuidor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poblaciones_vendedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Población",
                "verbose_name_plural": "Poblaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ClienteSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                (
                    "condicion_pago",
                    models.CharField(
                        choices=[
                            ("contado", "Contado"),
                            ("5d", "5 días"),
                            ("15d", "15 días"),
                            ("30d", "30 días"),
                        ],
                        default="contado",
                        max_length=10,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "poblacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="clientes.poblacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal de Cliente",
                "verbose_name_plural": "Sucursales de Clientes",
                "indexes": [
                    models.Index(
                        fields=["poblacion", "codigo"],
                        name="clientes_cl_poblaci_605f26_idx",
                    ),
                    models.Index(
                        fields=["cliente", "codigo"],
                        name="clientes_cl_cliente_d21a6b_idx",
                    ),
                ],
                "unique_together": {("cliente", "poblacion", "codigo")},
            },
        ),
    ]
