# Generated by Django 5.2.6 on 2025-10-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_poblacion_clientesucursal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientesucursal",
            name="condicion_pago",
            field=models.CharField(
                choices=[
                    ("contado", "Contado"),
                    ("15d", "15 días"),
                    ("10d", "10 días"),
                    ("5d", "5 días"),
                    ("30d", "30 días"),
                ],
                default="contado",
                max_length=10,
            ),
        ),
    ]
