# Generated by Django 5.2.6 on 2025-10-23 14:07

from django.db import migrations, models
from django.core.exceptions import ValidationError


def check_unique_codigo(apps, schema_editor):
    ClienteSucursal = apps.get_model('clientes', 'ClienteSucursal')
    from django.db.models import Count
    dups = (
        ClienteSucursal.objects.values('codigo')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    if dups.exists():
        detalles = []
        for d in dups:
            cod = d['codigo']
            ids = list(
                ClienteSucursal.objects.filter(codigo=cod).values_list('id', flat=True)
            )
            detalles.append(f"codigo={cod} ids={ids}")
        msg = (
            "No se puede aplicar la unicidad global de 'codigo' en ClienteSucursal porque hay "
            "códigos duplicados existentes. Por favor, resuélvalos antes de migrar. Duplicados: "
            + "; ".join(detalles)
        )
        raise ValidationError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_alter_clientesucursal_condicion_pago"),
    ]

    operations = [
        migrations.RunPython(check_unique_codigo, reverse_code=migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="clientesucursal",
            name="clientes_cl_poblaci_605f26_idx",
        ),
        migrations.RemoveIndex(
            model_name="clientesucursal",
            name="clientes_cl_cliente_d21a6b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="clientesucursal",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="clientesucursal",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="clientesucursal",
            index=models.Index(
                fields=["poblacion"], name="clientes_cl_poblaci_f08908_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientesucursal",
            index=models.Index(
                fields=["cliente"], name="clientes_cl_cliente_350882_idx"
            ),
        ),
    ]
