# Generated by Django 5.2.6 on 2025-10-09 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("facturas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factura",
            options={"ordering": ["-fecha_emision"]},
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("parcial", "Pago Parcial"),
                    ("pagada", "Pagada"),
                    ("vencida", "Vencida"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["numero_factura"], name="facturas_fa_numero__8c84bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["cliente", "estado"], name="facturas_fa_cliente_cf1bb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["vendedor", "estado"], name="facturas_fa_vendedo_9689f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["fecha_vencimiento"], name="facturas_fa_fecha_v_c2133c_idx"
            ),
        ),
    ]
