# Generated by Django 5.2.6 on 2025-10-16 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("facturas", "0003_facturaimportacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="tipo",
            field=models.CharField(
                choices=[("FE", "Factura Electrónica"), ("R", "Remisión")],
                default="FE",
                help_text="Tipo de factura: FE (Factura Electrónica) o R (Remisión)",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(fields=["tipo"], name="facturas_fa_tipo_53a908_idx"),
        ),
    ]
