# Generated by Django 5.2.6 on 2025-10-21 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facturas", "0004_factura_tipo_factura_facturas_fa_tipo_53a908_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="entrega_actualizado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="entrega_actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_entrega_actualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="estado_entrega",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente por entregar"),
                    ("entregado", "Entregado"),
                    ("devolucion_total", "Devolución total"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
