# Generated by Django 5.2.6 on 2025-10-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_poblacion_clientesucursal"),
        ("facturas", "0005_factura_entrega_actualizado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cliente_sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="clientes.clientesucursal",
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["cliente_sucursal"], name="facturas_fa_cliente_b07005_idx"
            ),
        ),
    ]
